"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export function RefreshProcess({ id }: { id: string }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function refresh() { setBusy(true); const response = await fetch(`/api/v1/processes/${id}/refresh`, { method: "POST" }); const result = await response.json(); setBusy(false); setMessage(response.ok ? (result.queued ? "Sincronização agendada." : "Sincronização já agendada.") : result.error); router.refresh(); }
  return <div><button className="button" onClick={refresh} disabled={busy}>{busy ? "Agendando…" : "Atualizar DataJud"}</button>{message && <p className="mt-2 text-xs font-semibold" role="status">{message}</p>}</div>;
}

export function RiskForm({ id, current }: { id: string; current: string }) {
  const [message, setMessage] = useState(""); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/v1/processes/${id}/risk`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ level: form.get("level"), probability: form.get("probability") ? Number(form.get("probability")) : null, impact: form.get("impact") ? Number(form.get("impact")) : null, reason: form.get("reason") }) }); const result = await response.json(); setMessage(response.ok ? "Risco atualizado e registrado." : result.error); if (response.ok) router.refresh(); }
  return <form className="card grid gap-4 p-4 md:grid-cols-2" onSubmit={submit}><label><span className="label">Nível</span><select className="field" name="level" defaultValue={current}><option value="low">Baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="critical">Crítico</option></select></label><label><span className="label">Probabilidade (%)</span><input className="field" name="probability" type="number" min="0" max="100" step="0.01" /></label><label><span className="label">Impacto (R$)</span><input className="field" name="impact" type="number" min="0" step="0.01" /></label><label><span className="label">Motivo obrigatório</span><input className="field" name="reason" minLength={3} required /></label><button className="button md:col-span-2">Registrar alteração</button>{message && <p role="status" className="md:col-span-2 text-sm font-semibold">{message}</p>}</form>;
}

export function ProcessEditForm({id,initial}:{id:string;initial:{status:string;notes?:string|null;monitoring_enabled:boolean;monitoring_frequency:string}}){const[message,setMessage]=useState("");const router=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),response=await fetch(`/api/v1/processes/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:f.get("status"),notes:f.get("notes")||null,monitoring_enabled:f.get("monitoring_enabled")==="on",monitoring_frequency:f.get("monitoring_frequency")})}),body=await response.json();setMessage(response.ok?"Processo atualizado.":body.error);if(response.ok)router.refresh()}return <form className="card grid gap-3 p-4 md:grid-cols-2" onSubmit={submit}><label><span className="label">Status</span><select className="field" name="status" defaultValue={initial.status}><option value="draft">Rascunho</option><option value="active">Ativo</option><option value="suspended">Suspenso</option><option value="closed">Encerrado</option><option value="archived">Arquivado</option></select></label><label><span className="label">Frequência de monitoramento</span><select className="field" name="monitoring_frequency" defaultValue={initial.monitoring_frequency}><option value="0 * * * *">A cada hora</option><option value="0 6,10,14,18 * * *">06h, 10h, 14h e 18h</option><option value="0 6,18 * * *">06h e 18h</option><option value="0 6 * * *">Diário às 06h</option><option value="0 8 * * *">Diário às 08h</option></select></label><label className="flex items-center gap-2"><input type="checkbox" name="monitoring_enabled" defaultChecked={initial.monitoring_enabled}/> Monitoramento ativo</label><textarea className="field min-h-28 md:col-span-2" name="notes" defaultValue={initial.notes??""} placeholder="Observações internas"/><button className="button md:col-span-2">Salvar processo</button>{message&&<p className="md:col-span-2 text-sm font-semibold">{message}</p>}</form>}

export function FinancialForm({id}:{id:string}){const[message,setMessage]=useState("");const router=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),response=await fetch(`/api/v1/processes/${id}/financial`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({field:f.get("field"),amount:Number(f.get("amount")),reason:f.get("reason")})}),body=await response.json();setMessage(response.ok?"Valor atualizado e registrado.":body.error);if(response.ok)router.refresh()}return <form className="card grid gap-3 p-4 md:grid-cols-3" onSubmit={submit}><select className="field" name="field"><option value="claim_value">Valor da causa</option><option value="estimated_exposure">Exposição estimada</option><option value="provision">Provisão</option><option value="settlement_value">Acordo</option><option value="paid_value">Pago</option><option value="recovered_value">Recuperado</option></select><input className="field" name="amount" type="number" min="0" step="0.01" required/><input className="field" name="reason" minLength={3} placeholder="Motivo obrigatório" required/><button className="button md:col-span-3">Registrar valor</button>{message&&<p className="md:col-span-3 text-sm font-semibold">{message}</p>}</form>}
