"use server";
import{revalidatePath}from"next/cache";import{z}from"zod";import{requirePermission}from"@/lib/auth";import{audit}from"@/lib/security";import{createAdminClient}from"@/lib/supabase/admin";import{createClient}from"@/lib/supabase/server";
export async function inviteUser(form:FormData){await requirePermission("admin.users");const input=z.object({email:z.email(),full_name:z.string().trim().min(2).max(160),role_id:z.uuid()}).parse(Object.fromEntries(form)),admin=createAdminClient(),{data,error}=await admin.auth.admin.inviteUserByEmail(input.email,{data:{full_name:input.full_name},redirectTo:`${process.env.NEXT_PUBLIC_APP_URL}/auth/callback`});if(error||!data.user)throw new Error("Não foi possível convidar usuário");const{error:profileError}=await admin.from("profiles").update({role_id:input.role_id,full_name:input.full_name}).eq("id",data.user.id);if(profileError){await admin.auth.admin.deleteUser(data.user.id);throw new Error("Não foi possível atribuir o perfil do usuário")}await audit("invite","user",data.user.id);revalidatePath("/admin")}
export async function changeUserRole(form:FormData){await requirePermission("admin.users");const input=z.object({user_id:z.uuid(),role_id:z.uuid(),active:z.enum(["true","false"])}).parse(Object.fromEntries(form)),supabase=await createClient(),{error}=await supabase.from("profiles").update({role_id:input.role_id,active:input.active==="true"}).eq("id",input.user_id);if(error)throw new Error("Não foi possível atualizar usuário");await audit("permission_change","user",input.user_id);revalidatePath("/admin")}
export async function togglePermission(form:FormData){await requirePermission("admin.users");const input=z.object({role_id:z.uuid(),permission_id:z.uuid(),enabled:z.enum(["true","false"])}).parse(Object.fromEntries(form)),supabase=await createClient();if(input.enabled==="true"){const{error}=await supabase.from("role_permissions").upsert({role_id:input.role_id,permission_id:input.permission_id});if(error)throw error}else{const{error}=await supabase.from("role_permissions").delete().eq("role_id",input.role_id).eq("permission_id",input.permission_id);if(error)throw error}await audit("permission_change","role",input.role_id,{permission_id:input.permission_id,enabled:input.enabled});revalidatePath("/admin")}
export async function createCategory(form:FormData){await requirePermission("admin.settings");const name=z.string().trim().min(2).max(120).parse(form.get("name")),supabase=await createClient(),{data,error}=await supabase.from("categories").insert({name}).select("id").single();if(error)throw new Error("Categoria já existe ou é inválida");await audit("create","category",data.id);revalidatePath("/admin")}
const allowedSettings=new Set(["monitoring.default_schedule","jobs.max_attempts","retention.audit_days","retention.conversation_days","retention.document_days","retention.temporary_days","ai.model","ai.temperature","ai.max_tokens","ai.features_enabled"]);
export async function updateSetting(form:FormData){const{user}=await requirePermission("admin.settings");const key=z.string().parse(form.get("key"));if(!allowedSettings.has(key))throw new Error("Configuração não permitida");const raw=z.string().max(1000).parse(form.get("value"));let value:unknown;try{value=JSON.parse(raw)}catch{value=raw}const supabase=await createClient(),{error}=await supabase.from("system_settings").update({value,updated_by:user.id}).eq("key",key).eq("sensitive",false);if(error)throw new Error("Não foi possível salvar configuração");await audit("update","system_setting",key);revalidatePath("/admin")}
export async function updateNotificationPreferences(form:FormData){const{user}=await requirePermission("alert.read");const channels=(name:string)=>form.getAll(name).map(String).filter(v=>["in_app","email","teams","webhook"].includes(v));const supabase=await createClient(),{error}=await supabase.from("notification_preferences").upsert({user_id:user.id,urgent_channels:channels("urgent"),attention_channels:channels("attention"),informative_channels:channels("informative"),daily_digest_time:String(form.get("daily_digest_time")||"08:00"),timezone:"America/Sao_Paulo"});if(error)throw new Error("Não foi possível salvar preferências");revalidatePath("/admin")}
