import "server-only";
import { z } from "zod";
import type { AiTool } from "@/lib/ai/client";
import { MimoClient } from "@/lib/ai/client";
import { createClient } from "@/lib/supabase/server";

type Source = { type: string; id?: string; label: string; excerpt?: string };
export type ToolResult = { data: unknown; sources: Source[] };
const uuid = z.uuid();
const page = z.number().int().min(1).max(100).default(1);

function tool(name: string, description: string, properties: Record<string, unknown>, required: string[] = []): AiTool {
  return { type: "function", function: { name, description, parameters: { type: "object", additionalProperties: false, properties, required } } };
}
const string = { type: "string" }; const id = { type: "string", format: "uuid" };
export const LEGAL_TOOLS: AiTool[] = [
  tool("search_processes","Busca processos internos por CNJ, tribunal, categoria ou status",{query:string,status:string,risk:string,page:{type:"integer",minimum:1}}),
  tool("get_process","Obtém processo interno por ID",{process_id:id},["process_id"]),
  tool("get_process_movements","Lista movimentações persistidas",{process_id:id,page:{type:"integer",minimum:1}},["process_id"]),
  tool("refresh_process","Agenda sincronização DataJud/MCP",{process_id:id},["process_id"]),
  tool("get_process_deadlines","Lista prazos do processo",{process_id:id},["process_id"]),
  tool("get_tasks","Lista tarefas, opcionalmente do processo",{process_id:id,status:string}),
  tool("create_task","Cria tarefa interna",{process_id:id,title:string,description:string,due_at:string,priority:{type:"string",enum:["low","medium","high","urgent"]}},["title"]),
  tool("create_deadline_draft","Cria sugestão de prazo pendente de confirmação",{process_id:id,title:string,description:string,due_at:string,priority:{type:"string",enum:["low","medium","high","urgent"]},source_id:id},["process_id","title","due_at"]),
  tool("search_documents","Busca híbrida em documentos autorizados",{query:string,process_id:id,limit:{type:"integer",minimum:1,maximum:20}},["query"]),
  tool("get_document","Obtém metadados e texto extraído",{document_id:id},["document_id"]),
  tool("search_similar_cases","Busca casos semelhantes por conteúdo",{query:string,category_id:id,limit:{type:"integer",minimum:1,maximum:20}},["query"]),
  tool("search_internal_notes","Busca notas internas",{query:string,process_id:id},["query"]),
  tool("get_dashboard_metrics","Obtém métricas jurídicas consolidadas",{}),
  tool("get_risk_data","Obtém processos e histórico por risco",{process_id:id,risk:{type:"string",enum:["low","medium","high","critical"]}}),
  tool("get_financial_exposure","Obtém valores calculados pelo banco",{company_id:id,category_id:id}),
  tool("search_parties","Busca partes processuais",{query:string},["query"]),
  tool("generate_report_data","Obtém dados estruturados para relatório",{type:string,start_date:string,end_date:string},["type"])
];

export async function executeLegalTool(name: string, raw: unknown, userId: string): Promise<ToolResult> {
  const supabase = await createClient(); const args = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  if (name === "search_processes") {
    const input=z.object({query:z.string().max(200).optional(),status:z.string().optional(),risk:z.string().optional(),page:page.optional()}).parse(args);let q=supabase.from("processes").select("id,process_number,status,risk_level,court_name,judicial_class,estimated_exposure,provision,last_synced_at",{count:"exact"}).is("deleted_at",null);if(input.query)q=q.or(`process_number.ilike.%${input.query.replace(/[%_,()]/g,"")}%,court_name.ilike.%${input.query.replace(/[%_,()]/g,"")}%`);if(input.status)q=q.eq("status",input.status);if(input.risk)q=q.eq("risk_level",input.risk);const{data,error}=await q.range(((input.page??1)-1)*20,(input.page??1)*20-1);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"process",id:r.id,label:`Processo ${r.process_number}`}))};
  }
  if(name==="get_process"){const input=z.object({process_id:uuid}).parse(args);const{data,error}=await supabase.from("processes").select("*,companies(trade_name,legal_name),business_units(name),categories(name),profiles!processes_responsible_user_id_fkey(full_name),law_firms(name),process_parties(role,parties(name,type))").eq("id",input.process_id).is("deleted_at",null).single();if(error)throw error;return{data,sources:[{type:"process",id:data.id,label:`Processo ${data.process_number}`}]};}
  if(name==="get_process_movements"){const input=z.object({process_id:uuid,page:page.optional()}).parse(args);const{data,error}=await supabase.from("process_movements").select("id,movement_date,movement_type,description,source,ai_summary,ai_analysis").eq("process_id",input.process_id).order("movement_date",{ascending:false}).range(((input.page??1)-1)*50,(input.page??1)*50-1);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"movement",id:r.id,label:`${r.source} — movimentação ${new Date(r.movement_date).toLocaleDateString("pt-BR")}`,excerpt:r.description.slice(0,240)}))};}
  if(name==="refresh_process"){const input=z.object({process_id:uuid}).parse(args);const{data,error}=await supabase.rpc("enqueue_process_sync",{process_id:input.process_id,request_key:`ai-sync:${input.process_id}:${new Date().toISOString().slice(0,13)}`});if(error)throw error;return{data:{job_id:data,status:"queued"},sources:[{type:"process",id:input.process_id,label:"Solicitação de sincronização"}]};}
  if(name==="get_process_deadlines"){const input=z.object({process_id:uuid}).parse(args);const{data,error}=await supabase.from("deadlines").select("id,title,description,due_at,status,priority,origin,confirmed_at").eq("process_id",input.process_id).is("deleted_at",null).order("due_at");if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"deadline",id:r.id,label:`Prazo ${r.title} — ${r.status}`}))};}
  if(name==="get_tasks"){const input=z.object({process_id:uuid.optional(),status:z.string().optional()}).parse(args);let q=supabase.from("tasks").select("id,process_id,title,description,due_at,status,priority,origin").is("deleted_at",null);if(input.process_id)q=q.eq("process_id",input.process_id);if(input.status)q=q.eq("status",input.status);const{data,error}=await q.order("due_at").limit(100);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"task",id:r.id,label:`Tarefa ${r.title}`}))};}
  if(name==="create_task"){const input=z.object({process_id:uuid.optional(),title:z.string().min(2).max(200),description:z.string().max(2000).optional(),due_at:z.iso.datetime().optional(),priority:z.enum(["low","medium","high","urgent"]).default("medium")}).parse(args);const{data,error}=await supabase.from("tasks").insert({...input,process_id:input.process_id??null,due_at:input.due_at??null,description:input.description??null,created_by:userId,origin:"AI"}).select("id,title").single();if(error)throw error;return{data,sources:[{type:"task",id:data.id,label:`Tarefa criada: ${data.title}`}]};}
  if(name==="create_deadline_draft"){const input=z.object({process_id:uuid,title:z.string().min(2).max(200),description:z.string().max(2000).optional(),due_at:z.iso.datetime(),priority:z.enum(["low","medium","high","urgent"]).default("medium"),source_id:uuid.optional()}).parse(args);const{data,error}=await supabase.from("deadlines").insert({...input,description:input.description??null,source_id:input.source_id??null,created_by:userId,origin:"AI",status:"pending_confirmation"}).select("id,title,status").single();if(error)throw error;return{data,sources:[{type:"deadline",id:data.id,label:`Prazo sugerido: ${data.title} — PENDENTE DE CONFIRMAÇÃO`}]};}
  if(name==="search_documents"||name==="search_similar_cases"){const input=z.object({query:z.string().min(2).max(500),process_id:uuid.optional(),category_id:uuid.optional(),limit:z.number().int().min(1).max(20).default(10)}).parse(args);let embedding:number[]|null=null;try{embedding=await new MimoClient().embed(input.query)}catch{/* FTS remains available when embedding provider is unavailable. */}const{data,error}=await supabase.rpc("match_document_chunks",{query_text:input.query,query_embedding:embedding,match_count:input.limit,filter_process_id:input.process_id??null,filter_category_id:input.category_id??null});if(error)throw error;return{data,sources:(data??[]).map((r:{id:string;document_id:string;page?:number;content:string})=>({type:"document",id:r.document_id,label:`Documento ${r.document_id}${r.page?`, página ${r.page}`:""}`,excerpt:r.content.slice(0,240)}))};}
  if(name==="get_document"){const input=z.object({document_id:uuid}).parse(args);const{data,error}=await supabase.from("documents").select("id,name,type,mime_type,extracted_text,metadata,created_at,process_id").eq("id",input.document_id).is("deleted_at",null).single();if(error)throw error;return{data:{...data,extracted_text:data.extracted_text?.slice(0,20000)},sources:[{type:"document",id:data.id,label:data.name,excerpt:data.extracted_text?.slice(0,240)}]};}
  if(name==="search_internal_notes"){const input=z.object({query:z.string().min(2).max(300),process_id:uuid.optional()}).parse(args);let q=supabase.from("notes").select("id,process_id,content,created_at").ilike("content",`%${input.query.replace(/[%_]/g,"")}%`).is("deleted_at",null);if(input.process_id)q=q.eq("process_id",input.process_id);const{data,error}=await q.limit(30);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"note",id:r.id,label:"Nota interna",excerpt:r.content.slice(0,240)}))};}
  if(name==="get_dashboard_metrics"||name==="generate_report_data"){const now=new Date(),month=new Date(now.getFullYear(),now.getMonth(),1).toISOString();const[active,critical,deadlines,tasks,movements,values]=await Promise.all([supabase.from("processes").select("id",{count:"exact",head:true}).eq("status","active").is("deleted_at",null),supabase.from("processes").select("id",{count:"exact",head:true}).eq("risk_level","critical").is("deleted_at",null),supabase.from("deadlines").select("id",{count:"exact",head:true}).neq("status","completed").is("deleted_at",null),supabase.from("tasks").select("id",{count:"exact",head:true}).neq("status","completed").is("deleted_at",null),supabase.from("process_movements").select("id",{count:"exact",head:true}).gte("movement_date",month),supabase.from("processes").select("claim_value,estimated_exposure,provision").is("deleted_at",null)]);const totals=(values.data??[]).reduce((a,r)=>({claim:a.claim+Number(r.claim_value??0),exposure:a.exposure+Number(r.estimated_exposure??0),provision:a.provision+Number(r.provision??0)}),{claim:0,exposure:0,provision:0});return{data:{active:active.count??0,critical:critical.count??0,open_deadlines:deadlines.count??0,open_tasks:tasks.count??0,movements_this_month:movements.count??0,...totals,generated_at:now.toISOString()},sources:[{type:"database",label:"Supabase — métricas calculadas"}]};}
  if(name==="get_risk_data"){const input=z.object({process_id:uuid.optional(),risk:z.enum(["low","medium","high","critical"]).optional()}).parse(args);let q=supabase.from("processes").select("id,process_number,risk_level,probability,impact,estimated_exposure,provision").is("deleted_at",null);if(input.process_id)q=q.eq("id",input.process_id);if(input.risk)q=q.eq("risk_level",input.risk);const{data,error}=await q.limit(100);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"process",id:r.id,label:`Risco do processo ${r.process_number}`}))};}
  if(name==="get_financial_exposure"){const input=z.object({company_id:uuid.optional(),category_id:uuid.optional()}).parse(args);let q=supabase.from("processes").select("id,process_number,claim_value,estimated_exposure,provision,settlement_value,paid_value,recovered_value").is("deleted_at",null);if(input.company_id)q=q.eq("company_id",input.company_id);if(input.category_id)q=q.eq("category_id",input.category_id);const{data,error}=await q.limit(500);if(error)throw error;const totals=(data??[]).reduce((a,r)=>({claim:a.claim+Number(r.claim_value??0),exposure:a.exposure+Number(r.estimated_exposure??0),provision:a.provision+Number(r.provision??0),paid:a.paid+Number(r.paid_value??0),recovered:a.recovered+Number(r.recovered_value??0)}),{claim:0,exposure:0,provision:0,paid:0,recovered:0});return{data:{totals,processes:data},sources:[{type:"database",label:"Supabase — exposição financeira"}]};}
  if(name==="search_parties"){const input=z.object({query:z.string().min(2).max(200)}).parse(args);const{data,error}=await supabase.from("parties").select("id,name,type,document_masked,process_parties(process_id,role)").ilike("name",`%${input.query.replace(/[%_]/g,"")}%`).limit(50);if(error)throw error;return{data,sources:(data??[]).map(r=>({type:"party",id:r.id,label:`Parte ${r.name}`}))};}
  throw new Error("Ferramenta não autorizada");
}
